# Generated by Django 3.0.8 on 2020-07-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='middlepoint',
            name='username',
            field=models.CharField(default=-1.0, max_length=200),
            preserve_default=False,
        ),
    ]
