# Generated by Django 3.0.8 on 2020-07-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_middlepoint_middle_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='middlepoint',
            name='infomarti',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='middlepoint',
            name='middle_points',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='middlepoint',
            name='type_of_point',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
